var conanData = [
    {
        "index": 1,
        "episode": 1,
        "episode_kr": "1기 1화",
        "title_kr": "눈물의 진주목걸이",
        "title_jp": "제트코스터 살인사건",
        "namu": "https:\/\/namu.wiki\/w\/%EC%A0%9C%ED%8A%B8%20%EC%BD%94%EC%8A%A4%ED%84%B0%20%EC%82%B4%EC%9D%B8%EC%82%AC%EA%B1%B4",
        "count": 1,
        "epSortation1": "#",
        "epSortation2": "#",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003847034",
        "url_tving_jp2": "#",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 2,
        "episode": 2,
        "episode_kr": "1기 2화",
        "title_kr": "이슬이를 찾아라",
        "title_jp": "사장 영애 유괴사건",
        "namu": "https:\/\/namu.wiki\/w\/%EC%82%AC%EC%9E%A5%20%EC%98%81%EC%95%A0%20%EC%9C%A0%EA%B4%B4%EC%82%AC%EA%B1%B4",
        "count": 1,
        "epSortation1": "#",
        "epSortation2": "#",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003847035",
        "url_tving_jp2": "#",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 3,
        "episode": 11,
        "episode_kr": "1기 13화~14화",
        "title_kr": "월광 소나타",
        "title_jp": "피아노 소나타 월광 살인사건",
        "namu": "https:\/\/namu.wiki\/w\/%ED%94%BC%EC%95%84%EB%85%B8%20%EC%86%8C%EB%82%98%ED%83%80%20%E3%80%8E%EC%9B%94%EA%B4%91%E3%80%8F%20%EC%82%B4%EC%9D%B8%EC%82%AC%EA%B1%B4",
        "count": 2,
        "epSortation1": "상편",
        "epSortation2": "하편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003853541",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003853542",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 4,
        "episode": 43,
        "episode_kr": "1기 31화",
        "title_kr": "가짜 엄마 소동",
        "title_jp": "에도가와 코난 유괴사건",
        "namu": "https:\/\/namu.wiki\/w\/%EC%97%90%EB%8F%84%EA%B0%80%EC%99%80%20%EC%BD%94%EB%82%9C%20%EC%9C%A0%EA%B4%B4%EC%82%AC%EA%B1%B4",
        "count": 1,
        "epSortation1": "#",
        "epSortation2": "#",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003868491",
        "url_tving_jp2": "#",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 5,
        "episode": 48,
        "episode_kr": "1기 35화~36화",
        "title_kr": "돌아온 남도일",
        "title_jp": "외교관 살인사건",
        "namu": "https:\/\/namu.wiki\/w\/%EC%99%B8%EA%B5%90%EA%B4%80%20%EC%82%B4%EC%9D%B8%EC%82%AC%EA%B1%B4",
        "count": 2,
        "epSortation1": "상편",
        "epSortation2": "하편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003871927",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003871928",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 6,
        "episode": 54,
        "episode_kr": "1기 40화",
        "title_kr": "뒤바뀐 가방",
        "title_jp": "게임 회사 살인사건",
        "namu": "https:\/\/namu.wiki\/w\/%EA%B2%8C%EC%9E%84%20%ED%9A%8C%EC%82%AC%20%EC%82%B4%EC%9D%B8%EC%82%AC%EA%B1%B4",
        "count": 1,
        "epSortation1": "#",
        "epSortation2": "#",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003875430",
        "url_tving_jp2": "#",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 7,
        "episode": 57,
        "episode_kr": "1기 43화~44화",
        "title_kr": "추리여행에서 생긴 일",
        "title_jp": "홈즈 프리크 살인사건",
        "namu": "https:\/\/namu.wiki\/w\/%ED%99%88%EC%A6%88%20%ED%94%84%EB%A6%AC%ED%81%AC%20%EC%82%B4%EC%9D%B8%EC%82%AC%EA%B1%B4",
        "count": 2,
        "epSortation1": "상편",
        "epSortation2": "하편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003878420",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003878821",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 8,
        "episode": 76,
        "episode_kr": "1기 55화~56화",
        "title_kr": "코난 대 괴도키드",
        "title_jp": "코난 vs 괴도 키드",
        "namu": "https:\/\/namu.wiki\/w\/%EC%BD%94%EB%82%9C%20vs%20%EA%B4%B4%EB%8F%84%20%ED%82%A4%EB%93%9C",
        "count": 2,
        "epSortation1": "상편",
        "epSortation2": "하편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003889119",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003889120",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 9,
        "episode": 118,
        "episode_kr": "SPECIAL EPISODE",
        "title_kr": "복수의 연쇄 살인 사건",
        "title_jp": "나니와의 연속 살인사건",
        "namu": "https:\/\/namu.wiki\/w\/%EB%82%98%EB%8B%88%EC%99%80%EC%9D%98%20%EC%97%B0%EC%86%8D%20%EC%82%B4%EC%9D%B8%EC%82%AC%EA%B1%B4",
        "count": 1,
        "epSortation1": "#",
        "epSortation2": "#",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003923617",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003923618",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 10,
        "episode": 128,
        "episode_kr": "2기 26화",
        "title_kr": "10억원 강도사건",
        "title_jp": "검은 조직 10억 엔 강탈사건",
        "namu": "https:\/\/namu.wiki\/w\/%EA%B8%B0%EB%AC%98%ED%95%9C%20%EC%82%AC%EB%9E%8C%20%EC%B0%BE%EA%B8%B0%20%EC%82%B4%EC%9D%B8%EC%82%AC%EA%B1%B4?from=%EA%B2%80%EC%9D%80%20%EC%A1%B0%EC%A7%81%2010%EC%96%B5%20%EC%97%94%20%EA%B0%95%ED%83%88%EC%82%AC%EA%B1%B4#s-4.2",
        "count": 1,
        "epSortation1": "#",
        "epSortation2": "#",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003933450",
        "url_tving_jp2": "#",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 11,
        "episode": 129,
        "episode_kr": "2기 27화~30화",
        "title_kr": "검은 조직에서 온 여자와",
        "title_jp": "검은 조직에서 온 여자,",
        "namu": "https:\/\/namu.wiki\/w\/%EA%B2%80%EC%9D%80%20%EC%A1%B0%EC%A7%81%EC%97%90%EC%84%9C%20%EC%98%A8%20%EC%97%AC%EC%9E%90%2C%20%EB%8C%80%ED%95%99%EA%B5%90%EC%88%98%20%EC%82%B4%EC%9D%B8%EC%82%AC%EA%B1%B4",
        "count": 4,
        "epSortation1": "위조지폐 사건(전편)",
        "epSortation2": "위조지폐 사건(후편)",
        "epSortation3": "대학교수 살인사건(전편)",
        "epSortation4": "대학교수 살인사건(후편)",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003934685",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003934686",
        "url_tving_jp3": "https:\/\/www.tving.com\/player\/E003937272",
        "url_tving_jp4": "https:\/\/www.tving.com\/player\/E003937273",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 12,
        "episode": 130,
        "episode_kr": "2기 31화~32화",
        "title_kr": "경기장 협박사건",
        "title_jp": "경기장 무차별 협박사건",
        "namu": "#",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003938084",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003938903",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 13,
        "episode": 136,
        "episode_kr": "2기 37화~38화",
        "title_kr": "유령 성 대모험",
        "title_jp": "푸른 고성 탐색 사건",
        "namu": "https:\/\/namu.wiki\/w\/%ED%91%B8%EB%A5%B8%20%EA%B3%A0%EC%84%B1%20%ED%83%90%EC%83%89%20%EC%82%AC%EA%B1%B4",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003943399",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003943400",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 14,
        "episode": 162,
        "episode_kr": "3기 13화~14회",
        "title_kr": "하늘을 나는 밀실 남도일 최초의 사건",
        "title_jp": "하늘 나는 밀실 쿠도 신이치 최초의 사건",
        "namu": "https:\/\/namu.wiki\/w\/%ED%95%98%EB%8A%98%20%EB%82%98%EB%8A%94%20%EB%B0%80%EC%8B%A4%20%EC%BF%A0%EB%8F%84%20%EC%8B%A0%EC%9D%B4%EC%B9%98%20%EC%B5%9C%EC%B4%88%EC%9D%98%20%EC%82%AC%EA%B1%B4",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003923097",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003923098",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 15,
        "episode": 170,
        "episode_kr": "미공개 X파일 1기 35~36화",
        "title_kr": "어둠 속의 사각",
        "title_jp": "어둠 속의 사각",
        "namu": "https:\/\/namu.wiki\/w\/%EC%96%B4%EB%91%A0%20%EC%86%8D%EC%9D%98%20%EC%82%AC%EA%B0%81",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003627451",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003627452",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 16,
        "episode": 176,
        "episode_kr": "3기 18화~20화",
        "title_kr": "검은 조직과의 재회",
        "title_jp": "검은 조직과의 재회",
        "namu": "https:\/\/namu.wiki\/w\/%EA%B2%80%EC%9D%80%20%EC%A1%B0%EC%A7%81%EA%B3%BC%EC%9D%98%20%EC%9E%AC%ED%9A%8C",
        "count": 3,
        "epSortation1": "홍장미 편",
        "epSortation2": "코난 편",
        "epSortation3": "해결 편",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003926728",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003926992",
        "url_tving_jp3": "https:\/\/www.tving.com\/player\/E003926991",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 17,
        "episode": 188,
        "episode_kr": "3기 30화~35화",
        "title_kr": "목숨을 건 부활",
        "title_jp": "목숨을 건 부활",
        "namu": "https:\/\/namu.wiki\/w\/%EB%AA%A9%EC%88%A8%EC%9D%84%20%EA%B1%B4%20%EB%B6%80%ED%99%9C",
        "count": 6,
        "epSortation1": "동굴의 탐정단",
        "epSortation2": "부상당한 명탐정",
        "epSortation3": "3제의 선택",
        "epSortation4": "검은 옷의 기사",
        "epSortation5": "돌아온 신이치",
        "epSortation6": "약속의 장소",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003937390",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003937863",
        "url_tving_jp3": "https:\/\/www.tving.com\/player\/E003937864",
        "url_tving_jp4": "https:\/\/www.tving.com\/player\/E003940612",
        "url_tving_jp5": "https:\/\/www.tving.com\/player\/E003940613",
        "url_tving_jp6": "https:\/\/www.tving.com\/player\/E003940892"
 },
    {
        "index": 18,
        "episode": 219,
        "episode_kr": "4기 9화~12화",
        "title_kr": "모여든 명탐정! 남대일 대 괴도키드",
        "title_jp": "모여든 명탐정! 쿠도 신이치vs괴도 키드",
        "namu": "https:\/\/namu.wiki\/w\/%EB%AA%A8%EC%97%AC%EB%93%A0%20%EB%AA%85%ED%83%90%EC%A0%95!%20%EC%BF%A0%EB%8F%84%20%EC%8B%A0%EC%9D%B4%EC%B9%98vs%EA%B4%B4%EB%8F%84%20%ED%82%A4%EB%93%9C",
        "count": 4,
        "epSortation1": "첫 번째 이야기",
        "epSortation2": "두 번째 이야기",
        "epSortation3": "세 번째 이야기",
        "epSortation4": "마지막 이야기",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E001072396",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E001072393",
        "url_tving_kr3": "https:\/\/www.tving.com\/player\/E001072394",
        "url_tving_kr4": "https:\/\/www.tving.com\/player\/E001072395",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003962374",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003962377",
        "url_tving_jp3": "https:\/\/www.tving.com\/player\/E003974984",
        "url_tving_jp4": "https:\/\/www.tving.com\/player\/E003974985",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 19,
        "episode": 222,
        "episode_kr": "4기 5화~7화",
        "title_kr": "그리고 인어는 사라져 버렸다",
        "title_jp": "그리고 인어는 사라져 버렸다",
        "namu": "https:\/\/namu.wiki\/w\/%EA%B7%B8%EB%A6%AC%EA%B3%A0%20%EC%9D%B8%EC%96%B4%EB%8A%94%20%EC%82%AC%EB%9D%BC%EC%A0%B8%20%EB%B2%84%EB%A0%B8%EB%8B%A4",
        "count": 3,
        "epSortation1": "사건편",
        "epSortation2": "추리편",
        "epSortation3": "해결편",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E001206692",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E001206693",
        "url_tving_kr3": "https:\/\/www.tving.com\/player\/E001208823",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003979838",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003979839",
        "url_tving_jp3": "https:\/\/www.tving.com\/player\/E003982756",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 20,
        "episode": 226,
        "episode_kr": "4기 13화~14화",
        "title_kr": "격투게임의 함정",
        "title_jp": "베틀게임의 함정",
        "namu": "https:\/\/namu.wiki\/w\/%EB%B0%B0%ED%8B%80%EA%B2%8C%EC%9E%84%EC%9D%98%20%ED%95%A8%EC%A0%95",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E001215570",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E001215571",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003984151",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003984152",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 21,
        "episode": 230,
        "episode_kr": "4기 17화~18화",
        "title_kr": "수수께끼의 승객",
        "title_jp": "수수께끼의 승객",
        "namu": "https:\/\/namu.wiki\/w\/%EC%88%98%EC%88%98%EA%BB%98%EB%81%BC%EC%9D%98%20%EC%8A%B9%EA%B0%9D",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E001220043",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E001220044",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E004048119",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E004048120",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 22,
        "episode": 242,
        "episode_kr": "4기 29화",
        "title_kr": "뭉치의 수난시대",
        "title_jp": "겐타 소년의 재난",
        "namu": "https:\/\/namu.wiki\/w\/%EA%B2%90%ED%83%80%20%EC%86%8C%EB%85%84%EC%9D%98%20%EC%9E%AC%EB%82%9C",
        "count": 1,
        "epSortation1": "#",
        "epSortation2": "#",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E001232996",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E004059511",
        "url_tving_jp2": "#",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 23,
        "episode": 253,
        "episode_kr": "미공개 X파일 2기 3화~4화",
        "title_kr": "본청의 형사 사랑 이야기 4",
        "title_jp": "본청의 형사 사랑 이야기 4",
        "namu": "https:\/\/namu.wiki\/w\/%EB%AA%85%ED%83%90%EC%A0%95%20%EC%BD%94%EB%82%9C\/%EB%B3%B8%EC%B2%AD%EC%9D%98%20%ED%98%95%EC%82%AC%20%EC%82%AC%EB%9E%91%20%EC%9D%B4%EC%95%BC%EA%B8%B0#s-6",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003747142",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003747143",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 24,
        "episode": 258,
        "episode_kr": "4기 39화~40화",
        "title_kr": "시카고에서 온 남자",
        "title_jp": "시카고에서 온 남자",
        "namu": "https:\/\/namu.wiki\/w\/%EC%8B%9C%EC%B9%B4%EA%B3%A0%EC%97%90%EC%84%9C%20%EC%98%A8%20%EB%82%A8%EC%9E%90",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E001245333",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E001245334",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E004070846",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E004070847",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 25,
        "episode": 269,
        "episode_kr": "4기 51화~52화",
        "title_kr": "범죄의 사라진 증거",
        "title_jp": "범죄의 유품",
        "namu": "https:\/\/namu.wiki\/w\/%EB%B2%94%EC%A3%84%EC%9D%98%20%EC%9C%A0%ED%92%88",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E001259135",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E001259136",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E004082457",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E004082458",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 26,
        "episode": 271,
        "episode_kr": "미공개 X파일 2기 9화~10화",
        "title_kr": "가리고 서두르고 생략",
        "title_jp": "숨기도 서둘러 생략",
        "namu": "https:\/\/namu.wiki\/w\/%EC%88%A8%EA%B8%B0%EA%B3%A0%20%EC%84%9C%EB%91%98%EB%9F%AC%20%EC%83%9D%EB%9E%B5",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003752144",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003752003",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 27,
        "episode": 277,
        "episode_kr": "5기 4화~5화",
        "title_kr": "영어교사 vs 소년 명탐정",
        "title_jp": "영어교사vs서쪽의 명탐정",
        "namu": "https:\/\/namu.wiki\/w\/%EC%98%81%EC%96%B4%EA%B5%90%EC%82%ACvs%EC%84%9C%EC%AA%BD%EC%9D%98%20%EB%AA%85%ED%83%90%EC%A0%95",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E001512529",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E001528026",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003972866",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003979357",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 28,
        "episode": 284,
        "episode_kr": "5기 11화~12화",
        "title_kr": "차이나타운에 내리는 비의 데자뷰",
        "title_jp": "차이나타운, 비의 데자뷰",
        "namu": "https:\/\/namu.wiki\/w\/%EC%B0%A8%EC%9D%B4%EB%82%98%ED%83%80%EC%9A%B4%2C%20%EB%B9%84%EC%9D%98%20%EB%8D%B0%EC%9E%90%EB%B7%B0",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E001567642",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E001567643",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003983791",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003983792",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 29,
        "episode": 286,
        "episode_kr": "5기 13화~15화",
        "title_kr": "남도일의 뉴욕사건",
        "title_jp": "쿠도 신이치 NY의 사건",
        "namu": "https:\/\/namu.wiki\/w\/%EC%BF%A0%EB%8F%84%20%EC%8B%A0%EC%9D%B4%EC%B9%98%20%EB%89%B4%EC%9A%95%EC%9D%98%20%EC%82%AC%EA%B1%B4",
        "count": 3,
        "epSortation1": "사건편",
        "epSortation2": "추리편",
        "epSortation3": "해결편",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E001580138",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E001580139",
        "url_tving_kr3": "https:\/\/www.tving.com\/player\/E001595722",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E004046976",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E004046975",
        "url_tving_jp3": "https:\/\/www.tving.com\/player\/E004047640",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 30,
        "episode": 289,
        "episode_kr": "5기 16화~17화",
        "title_kr": "미로의 숲 속의 세모",
        "title_jp": "방황의 숲의 미츠히코",
        "namu": "https:\/\/namu.wiki\/w\/%EB%B0%A9%ED%99%A9%EC%9D%98%20%EC%88%B2%EC%9D%98%20%EB%AF%B8%EC%B8%A0%ED%9E%88%EC%BD%94",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E001595723",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E001611618",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E004047641",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E004051278",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 31,
        "episode": 304,
        "episode_kr": "5기 26화~29화",
        "title_kr": "춤추는 경찰청 천만 명의 인질",
        "title_jp": "흔들리는 경시청 1200만 명의 인질",
        "namu": "https:\/\/namu.wiki\/w\/%ED%9D%94%EB%93%A4%EB%A6%AC%EB%8A%94%20%EA%B2%BD%EC%8B%9C%EC%B2%AD%201200%EB%A7%8C%20%EB%AA%85%EC%9D%98%20%EC%9D%B8%EC%A7%88",
        "count": 4,
        "epSortation1": 1,
        "epSortation2": 2,
        "epSortation3": 3,
        "epSortation4": 4,
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E003611404",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E003611405",
        "url_tving_kr3": "https:\/\/www.tving.com\/player\/E003611440",
        "url_tving_kr4": "https:\/\/www.tving.com\/player\/E003611441",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E004058273",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E004058274",
        "url_tving_jp3": "https:\/\/www.tving.com\/player\/E004058275",
        "url_tving_jp4": "https:\/\/www.tving.com\/player\/E004060185",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 32,
        "episode": 307,
        "episode_kr": "미공개 X파일 2기 17화~18화",
        "title_kr": "남겨진 소리 없는 증언",
        "title_jp": "남겨진 소리 없는 증언",
        "namu": "https:\/\/namu.wiki\/w\/%EB%82%A8%EA%B2%A8%EC%A7%84%20%EC%86%8C%EB%A6%AC%20%EC%97%86%EB%8A%94%20%EC%A6%9D%EC%96%B8",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003758314",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003758316"
 },
    {
        "index": 33,
        "episode": 309,
        "episode_kr": "5기 32화~34화",
        "title_kr": "검은 조직과의 접촉",
        "title_jp": "검은 조직과의 접촉",
        "namu": "https:\/\/namu.wiki\/w\/%EA%B2%80%EC%9D%80%20%EC%A1%B0%EC%A7%81%EA%B3%BC%EC%9D%98%20%EC%A0%91%EC%B4%89",
        "count": 3,
        "epSortation1": "교섭편",
        "epSortation2": "추적편",
        "epSortation3": "결사편",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E003611444",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E003611445",
        "url_tving_kr3": "https:\/\/www.tving.com\/player\/E003611446",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E004063844",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E004066940",
        "url_tving_jp3": "https:\/\/www.tving.com\/player\/E004066943",
        "url_tving_jp4": "https:\/\/www.tving.com\/player\/E004066943",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 34,
        "episode": 312,
        "episode_kr": "미공개 X파일 2기 19화~20화",
        "title_kr": "석양에 물든 히나 인형",
        "title_jp": "석양에 물든 히나 인형",
        "namu": "https:\/\/namu.wiki\/w\/%EC%84%9D%EC%96%91%EC%97%90%20%EB%AC%BC%EB%93%A0%20%ED%9E%88%EB%82%98%20%EC%9D%B8%ED%98%95",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003758315",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003758317"
 },
    {
        "index": 35,
        "episode": 329,
        "episode_kr": "5기 48화~49화",
        "title_kr": "돈으로 살 수 없는 우정",
        "title_jp": "돈으로 살 수 없는 우정",
        "namu": "https:\/\/namu.wiki\/w\/%EB%8F%88%EC%9C%BC%EB%A1%9C%20%EC%82%B4%20%EC%88%98%20%EC%97%86%EB%8A%94%20%EC%9A%B0%EC%A0%95",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E003611460",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E003611461",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E004079568",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E004083006",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 36,
        "episode": 335,
        "episode_kr": "6기 3화~4화",
        "title_kr": "영화 현상소의 비밀",
        "title_jp": "동도현상소의 비밀",
        "namu": "#",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E003611467",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E003611468",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003530204",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003530205",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 37,
        "episode": 338,
        "episode_kr": "6기 5화~6화",
        "title_kr": "4대의 포르쉐",
        "title_jp": "4대의 포르쉐",
        "namu": "https:\/\/namu.wiki\/w\/4%EB%8C%80%EC%9D%98%20%ED%8F%AC%EB%A5%B4%EC%89%90",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E003611469",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E003611470",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003533102",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003532803",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 38,
        "episode": 340,
        "episode_kr": "6기 7화~8화",
        "title_kr": "화장실에 숨긴 비밀",
        "title_jp": "화장실에 숨긴 비밀",
        "namu": "https:\/\/namu.wiki\/w\/%ED%99%94%EC%9E%A5%EC%8B%A4%EC%97%90%20%EC%88%A8%EA%B8%B4%20%EB%B9%84%EB%B0%80",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E003611471",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E003611472",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003535661",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003535663",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 39,
        "episode": 343,
        "episode_kr": "6기 9화~10화",
        "title_kr": "편의점의 함정",
        "title_jp": "편의점의 함정",
        "namu": "https:\/\/namu.wiki\/w\/%ED%8E%B8%EC%9D%98%EC%A0%90%EC%9D%98%20%ED%95%A8%EC%A0%95",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E003611473",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E003611474",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003538562",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003538563",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 40,
        "episode": 345,
        "episode_kr": "6기 11화~15화",
        "title_kr": "검은 조직과의 정면 승부 보름달 두 개의 미스터리",
        "title_jp": "검은 조직과의 정면 승부 만월의 밤의 더블 미스터리",
        "namu": "https:\/\/namu.wiki\/w\/%EA%B2%80%EC%9D%80%20%EC%A1%B0%EC%A7%81%EA%B3%BC%EC%9D%98%20%EC%A0%95%EB%A9%B4%20%EC%8A%B9%EB%B6%80%20%EB%A7%8C%EC%9B%94%EC%9D%98%20%EB%B0%A4%EC%9D%98%20%EB%8D%94%EB%B8%94%20%EB%AF%B8%EC%8A%A4%ED%84%B0%EB%A6%AC",
        "count": 5,
        "epSortation1": "제 1부",
        "epSortation2": "제 2부",
        "epSortation3": "제 3부",
        "epSortation4": "제 4부",
        "epSortation5": "제 5부",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E003611475",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E003611476",
        "url_tving_kr3": "https:\/\/www.tving.com\/player\/E003611477",
        "url_tving_kr4": "https:\/\/www.tving.com\/player\/E003611478",
        "url_tving_kr5": "https:\/\/www.tving.com\/player\/E003611479",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003541685",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003541739",
        "url_tving_jp3": "https:\/\/www.tving.com\/player\/E003544596",
        "url_tving_jp4": "https:\/\/www.tving.com\/player\/E003544597",
        "url_tving_jp5": "https:\/\/www.tving.com\/player\/E003548718",
        "url_tving_jp6": "#"
 },
    {
        "index": 41,
        "episode": 346,
        "episode_kr": "6기 16화~17화",
        "title_kr": "엉덩이의 마크를 찾아라",
        "title_jp": "엉덩이의 마크를 찾아라",
        "namu": "https:\/\/namu.wiki\/w\/%EC%97%89%EB%8D%A9%EC%9D%B4%EC%9D%98%20%EB%A7%88%ED%81%AC%EB%A5%BC%20%EC%B0%BE%EC%95%84%EB%9D%BC",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E003611480",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E003611481",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003548719",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003551706",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 42,
        "episode": 361,
        "episode_kr": "6기 28화~29화",
        "title_kr": "고등학교의 괴담",
        "title_jp": "테이탄 고됴 학교 괴담",
        "namu": "https:\/\/namu.wiki\/w\/%ED%85%8C%EC%9D%B4%ED%83%84%EA%B3%A0%EA%B5%90%20%ED%95%99%EA%B5%90%20%EA%B4%B4%EB%8B%B4",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E003611491",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E003611492",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003567305",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003571449",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 43,
        "episode": 374,
        "episode_kr": "미공개 X파일 2기 29화~30화",
        "title_kr": "별과 담배의 암호",
        "title_jp": "별과 담배의 암호",
        "namu": "https:\/\/namu.wiki\/w\/%EB%B3%84%EA%B3%BC%20%EB%8B%B4%EB%B0%B0%EC%9D%98%20%EC%95%94%ED%98%B8",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003767876",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003767877",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 44,
        "episode": 385,
        "episode_kr": "6기 43화~45화",
        "title_kr": "스트라디바리우스의 불협화음",
        "title_jp": "스트라디바리우스의 불협화음",
        "namu": "https:\/\/namu.wiki\/w\/%EC%8A%A4%ED%8A%B8%EB%9D%BC%EB%94%94%EB%B0%94%EB%A6%AC%EC%9A%B0%EC%8A%A4%EC%9D%98%20%EB%B6%88%ED%98%91%ED%99%94%EC%9D%8C",
        "count": 3,
        "epSortation1": "전주곡",
        "epSortation2": "간주곡",
        "epSortation3": "후주곡",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E003611506",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E003611507",
        "url_tving_kr3": "https:\/\/www.tving.com\/player\/E003611508",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003596774",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003596775",
        "url_tving_jp3": "https:\/\/www.tving.com\/player\/E003598677",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 45,
        "episode": 394,
        "episode_kr": "미공개 X파일 2기 41화~43화",
        "title_kr": "기발한 저택에서의 대모험",
        "title_jp": "기발한 저택의 대모험",
        "namu": "https:\/\/namu.wiki\/w\/%EA%B8%B0%EB%B0%9C%ED%95%9C%20%EC%A0%80%ED%83%9D%EC%9D%98%20%EB%8C%80%EB%AA%A8%ED%97%98",
        "count": 3,
        "epSortation1": "봉인편",
        "epSortation2": "꼭두각시편",
        "epSortation3": "해결편",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "#",
        "url_tving_kr2": "#",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003777894",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003777895",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 46,
        "episode": 421,
        "episode_kr": "7기 21화~22화",
        "title_kr": "은행잎 색 첫사랑",
        "title_jp": "은행나무색의 첫사랑",
        "namu": "https:\/\/namu.wiki\/w\/%EC%9D%80%ED%96%89%EB%82%98%EB%AC%B4%20%EC%83%89%20%EC%B2%AB%EC%82%AC%EB%9E%91",
        "count": 2,
        "epSortation1": "전편",
        "epSortation2": "후편",
        "epSortation3": "#",
        "epSortation4": "#",
        "epSortation5": "#",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E003611517",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E003611518",
        "url_tving_kr3": "#",
        "url_tving_kr4": "#",
        "url_tving_kr5": "#",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003654375",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003654376",
        "url_tving_jp3": "#",
        "url_tving_jp4": "#",
        "url_tving_jp5": "#",
        "url_tving_jp6": "#"
 },
    {
        "index": 47,
        "episode": 425,
        "episode_kr": "7기 25화~29화",
        "title_kr": "블랙 임팩트! 조직의 손이 닿는 순간",
        "title_jp": "블랙 임팩트! 조직의 손이 닿는 순간",
        "namu": "https:\/\/namu.wiki\/w\/%EB%B8%94%EB%9E%99%20%EC%9E%84%ED%8C%A9%ED%8A%B8!%20%EC%A1%B0%EC%A7%81%EC%9D%98%20%EC%86%90%EC%9D%B4%20%EB%8B%BF%EB%8A%94%20%EC%88%9C%EA%B0%84",
        "count": 5,
        "epSortation1": "1부",
        "epSortation2": "2부",
        "epSortation3": "3부",
        "epSortation4": "4부",
        "epSortation5": "5부",
        "epSortation6": "#",
        "url_tving_kr1": "https:\/\/www.tving.com\/player\/E003611621",
        "url_tving_kr2": "https:\/\/www.tving.com\/player\/E003611622",
        "url_tving_kr3": "https:\/\/www.tving.com\/player\/E003611623",
        "url_tving_kr4": "https:\/\/www.tving.com\/player\/E003611624",
        "url_tving_kr5": "https:\/\/www.tving.com\/player\/E003611625",
        "url_tving_kr6": "#",
        "url_tving_jp1": "https:\/\/www.tving.com\/player\/E003660864",
        "url_tving_jp2": "https:\/\/www.tving.com\/player\/E003660865",
        "url_tving_jp3": "https:\/\/www.tving.com\/player\/E003664517",
        "url_tving_jp4": "https:\/\/www.tving.com\/player\/E003664518",
        "url_tving_jp5": "https:\/\/www.tving.com\/player\/E003667470",
        "url_tving_jp6": "#"
 }
]

var mainEpNum = 1;
var isNamdoilMode = true;

//기본 설정

//남도일 신이치 모드 변경
$("#btnradio1").on("click", function () {
    isNamdoilMode = true;
    DisplayInformationOnTheScreen(mainEpNum);
});
$("#btnradio2").on("click", function () {
    isNamdoilMode = false;
    DisplayInformationOnTheScreen(mainEpNum);
});





//이미지 슬라이드에 이미지 추가
for (var i = 0; i < 44; i++) {
    $('#mainThumbnail').append("<div class='carousel-item ep_img'><img src='img/" + conanData[i + 3].episode + ".webp' class='d-block w-100' alt='...'> </div>");
}

//이미지 슬라이드 움직임이 끝나면 정보표시
$('#carouselExampleControls').on('slid.bs.carousel', function (Event) {
    DisplayInformationOnTheScreen(Event.to);
    mainEpNum = Event.to;

})


//화면에 지금 에피소드 번호, 제목 등 표시하는 코드
function DisplayInformationOnTheScreen(epNum) {
    //console.log(epNum);
    $('#ep').text(conanData[epNum].episode + "화");
    $('#ep_kr').text(conanData[epNum].episode_kr);

    if (isNamdoilMode) {
        $('#ep_title').text(conanData[epNum].title_kr);
    } else {
        $('#ep_title').text(conanData[epNum].title_jp);
    }
}



//링크 복사
$("#copyLink").on("click", function () {
    // 현재 URL을 가져옵니다.
    const currentUrl = new URL(window.location.href);

    // 'ep' 파라미터를 설정합니다.
    currentUrl.searchParams.set('ep', mainEpNum + 1);

    // 수정된 URL을 문자열로 변환합니다.
    const newUrl = currentUrl.toString();

    // 클립보드에 복사하는 함수입니다.
    navigator.clipboard.writeText(newUrl).then(() => {
        showAlertCopySuccess(newUrl);
    }).catch(err => {
        showAlertCopyfailure(err);
    });

});



//복사 성공시 복사한 url 보이기
function showAlertCopySuccess(ShowUrl) {
    $("#copyAlert").append("<div class='alert alert-success d-flex align-items-center alert-dismissible fade show' role='alert'> <svg class='bi flex-shrink-0 me-2' width='24' height='24' role='img' aria-label='Success:'> <use xlink:href='#check-circle-fill' /> </svg> <div> <i class='bi bi-check-circle-fill'></i> URL이 클립보드에 복사되었습니다: " + ShowUrl + " </div><button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button> </div>");
}

//복사 실패시 경고창 보이기
function showAlertCopyfailure(showErr) {
    $("#copyAlert").append("<div class=‘alert alert-danger d-flex align-items-center alert-dismissible fade show’ role=‘alert’> <svg class=‘bi flex-shrink-0 me-2’ width=‘24’ height=‘24’ role=‘img’ aria-label=‘Danger:’> <use xlink:href=‘#exclamation-triangle-fill’ /> </svg> <div> <i class=‘bi bi-exclamation-triangle-fill’></i> example danger alert with an icon </div> <button type=‘button’ class=‘btn-close’ data-bs-dismiss=‘alert’ aria-label=‘Close’></button> </div> </div>");
}
